name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: read
  
jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4 
  # 1. Java 17 세팅 
  - name: Set up JDK 17
    uses: actions/setup-java@v4 
    with: 
      java-version: '17' 
      distribution: 'temurin' 

  # 2. Spring Boot 애플리케이션 빌드 
  - name: Build with Gradle 
    run: ./gradlew build 

  # 3. Docker 이미지 빌드 
  - name: docker image build 
    run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sample:0.0.2 .

  # 4. DockerHub 로그인 
  - name: docker login 
    uses: docker/login-action@v2 
    with: 
      username: ${{ secrets.DOCKERHUB_USERNAME }} 
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
  # 5. Docker Hub 이미지 푸시 
  - name: docker Hub push 
  run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sample:0.0.2
  
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted
    
    steps:
    # 1. 최신 이미지를 풀받습니다
    - name: docker pull
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sample:0.0.2
    # 2. 기존의 컨테이너를 중지시킵니다
    - name: docker stop container
      run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

    # 3. 최신 이미지를 컨테이너화하여 실행시킵니다
    - name: docker run new container
      run: sudo docker run --name sample --rm -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/sample:0.0.2

    # 4. 미사용 이미지를 정리합니다
    - name: delete old docker image
      run: sudo docker system prune -f  
    
