name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: read
  
jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted
    
    steps:
    # 1. 최신 이미지를 풀받습니다
    - name: docker pull
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sample:0.0.2
    # 2. 기존의 컨테이너를 중지시킵니다
    - name: docker stop container
      run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

    # 3. 최신 이미지를 컨테이너화하여 실행시킵니다
    - name: docker run new container
      run: sudo docker run --name sample --rm -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/sample:0.0.2

    # 4. 미사용 이미지를 정리합니다
    - name: delete old docker image
      run: sudo docker system prune -f  
    
